CREATE TABLE IF NOT EXISTS cliente (
id INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(50) NOT NULL,
telefone VARCHAR(11) NOT NULL UNIQUE,
email VARCHAR(100) NOT NULL UNIQUE,
cpf VARCHAR(11) NOT NULL UNIQUE,
cep VARCHAR(8) NOT NULL
);

CREATE TABLE IF NOT EXISTS aluguel (
id INT PRIMARY KEY AUTO_INCREMENT,
cliente_id INT NOT NULL,
data_inicio DATETIME NOT NULL,
data_devolução DATETIME NOT NULL,
pagamento INT NOT NULL,
valor DECIMAL(6,2) NOT NULL,
multa  BIT NOT NULL DEFAULT 0,
entregue BIT NOT NULL DEFAULT 0,

FOREIGN KEY (cliente_id) REFERENCES cliente (id)
);

CREATE TABLE IF NOT EXISTS jogo (
id INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(100) NOT NULL,
alugado BIT NOT NULL DEFAULT 0,
valor DECIMAL(6,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS aluguel_jogo (
    aluguel_id INT,
    jogo_id INT,
    PRIMARY KEY (aluguel_id, jogo_id),
    FOREIGN KEY (aluguel_id) REFERENCES aluguel(id),
    FOREIGN KEY (jogo_id) REFERENCES jogo(id)
);
